{{- if .Values.persistence.enabled }}
{{- range $component := list "web" "cron" "xmlrpc" "longpolling"  }}
{{- if (index $.Values.multiplePods $component).enabled | default true }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "odoo.fullname" $ }}-{{ $component }}-pvc
  labels:
{{ include "odoo.labels" $ | indent 4 }}
    component: {{ $component }}
spec:
  storageClassName: "{{ $.Values.persistence.storageClass }}"
  accessModes:
    - {{ $.Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ $.Values.persistence.size | quote }}
---
{{- end }}
{{- end }}
{{- end }}