{{- if .Values.multiplePods.enabled }}
{{- $xmlrpc := get .Values.multiplePods "xmlrpc" | default dict }}
{{- if $xmlrpc.enabled | default false }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-xmlrpc-service
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
    component: xmlrpc
spec:
  type: ClusterIP
  ports:
    - name: xmlrpc
      port: {{ .Values.multiplePods.xmlrpc.port | default 8069 }}
      targetPort: {{ .Values.multiplePods.xmlrpc.port | default 8069 }}
  selector:
    component: xmlrpc
    app.kubernetes.io/name: {{ include "odoo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
{{- end }}
