{{- if .Values.multiplePods.enabled }}
{{- $longpolling := get .Values.multiplePods "longpolling" | default dict }}
{{- if $longpolling.enabled | default false }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-longpolling-service
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
    component: longpolling
spec:
  type: ClusterIP
  ports:
    - name: longpolling-metrics
      port: 8072
      targetPort: 8072
  selector:
    component: longpolling
    app.kubernetes.io/name: {{ include "odoo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
{{- end }}
